/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CandidatoController;
import controller.EleitorController;
import java.awt.event.KeyEvent;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author user
 */
public class frmDiaCpf extends javax.swing.JDialog {

    /**
     * Creates new form frmDiaCpf
     */
    private static frmDiaCpfInvalido frmFilhoValidaCpf;
    private static frmPrincipal frmPai;
    private static frmDiaJaVotou frmFilhoJaVotou;
    public frmDiaCpf(frmPrincipal parent, boolean modal) {
        this.frmPai = parent;
        this.setModal(modal);
        initComponents();
        
        PromptSupport.setPrompt("Sem pontos ou traços", txtCpf);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT,txtCpf);
        txtCpf.setBorder(null);
        
    }
    
    public void destruir(){
    
        this.dispose();
        
    }
    
    public void buscaCf(){
    
        String cpf = txtCpf.getText();
        
        if(cpf.length()==11){
        
            try {
                
                EleitorController ec = new EleitorController();
                
                int valida = ec.controllerValidaCpf(cpf);
                
                if(valida == 0){
                
                    frmFilhoValidaCpf = new frmDiaCpfInvalido(null, true);
                    frmFilhoValidaCpf.setVisible(true);
                    
                    txtCpf.setText("");
                    
                }else{
                    
                    CandidatoController cc = new CandidatoController();
                    
                    int eleicao = cc.controllerRetornaId();
                    if(eleicao > 0){
                        int id = ec.controllerRetornaId(cpf);

                        int validaVoto = ec.controllerValidaVoto(eleicao, id);

                        if(validaVoto == 1){

                            frmFilhoJaVotou = new frmDiaJaVotou(null, true);

                            frmFilhoJaVotou.setVisible(true);

                            destruir();

                        }else{

                            frmVotacao frm = new frmVotacao();
                            frm.setVisible(true);
                            frm.recebeId(id, eleicao);
                            frmPai.destruirTela();
                            this.dispose();

                        }
                    }else{
                    
                        txtCpf.setText("");
                    
                    }
                }
                
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFechar = new javax.swing.JLabel();
        lblVotar = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        lblFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });
        getContentPane().add(lblFechar);
        lblFechar.setBounds(834, 200, 30, 30);

        lblVotar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVotar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVotarMouseClicked(evt);
            }
        });
        getContentPane().add(lblVotar);
        lblVotar.setBounds(710, 474, 152, 46);

        txtCpf.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        txtCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCpf.setBorder(null);
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpfKeyPressed(evt);
            }
        });
        getContentPane().add(txtCpf);
        txtCpf.setBounds(356, 324, 470, 66);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pu_votacao_index_cpf.png"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1200, 800);

        setSize(new java.awt.Dimension(1196, 797));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblFecharMouseClicked

    private void txtCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyPressed
        String cpf = txtCpf.getText();
        
        if((evt.getKeyCode()==KeyEvent.VK_LEFT)||(evt.getKeyCode()==KeyEvent.VK_RIGHT)
                ||(evt.getKeyCode()==KeyEvent.VK_DOWN)||(evt.getKeyCode()==KeyEvent.VK_UP)){
            
        }else if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            buscaCf();
        }else{
        
            int qtd = cpf.length();

            if(qtd > 10){

                cpf = cpf.substring(0, cpf.length()-1);

                txtCpf.setText(cpf);

            }
        }
    }//GEN-LAST:event_txtCpfKeyPressed

    private void lblVotarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVotarMouseClicked
        buscaCf();
    }//GEN-LAST:event_lblVotarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDiaCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDiaCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDiaCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDiaCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmDiaCpf dialog = new frmDiaCpf(frmPai, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblVotar;
    private javax.swing.JTextField txtCpf;
    // End of variables declaration//GEN-END:variables
}
