/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author user
 */
public class frmHome extends javax.swing.JFrame {

    private frmEleitoresInterno frmEleitores = new frmEleitoresInterno();
    private frmCandidatosInterno frmCandidatos = new frmCandidatosInterno();
    private frmRelatoriosInterno frmRelatorios = new frmRelatoriosInterno();
    private frmEleicaoInterno frmEleicao = new frmEleicaoInterno();
    public frmHome() {
        initComponents();
        jdpHome.add(frmEleitores);
        jdpHome.add(frmCandidatos);
        jdpHome.add(frmRelatorios);
        jdpHome.add(frmEleicao);
        frmEleicao.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSair = new javax.swing.JLabel();
        lblCandidatos = new javax.swing.JLabel();
        lblEleitores = new javax.swing.JLabel();
        lblRelatorios = new javax.swing.JLabel();
        lblIniciarEleicao = new javax.swing.JLabel();
        jdpHome = new javax.swing.JDesktopPane();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        lblSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
        });
        getContentPane().add(lblSair);
        lblSair.setBounds(666, 6, 26, 28);

        lblCandidatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCandidatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCandidatosMouseClicked(evt);
            }
        });
        getContentPane().add(lblCandidatos);
        lblCandidatos.setBounds(36, 6, 110, 30);

        lblEleitores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEleitores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEleitoresMouseClicked(evt);
            }
        });
        getContentPane().add(lblEleitores);
        lblEleitores.setBounds(216, 6, 110, 30);

        lblRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRelatoriosMouseClicked(evt);
            }
        });
        getContentPane().add(lblRelatorios);
        lblRelatorios.setBounds(396, 6, 110, 30);

        lblIniciarEleicao.setBackground(new java.awt.Color(255, 255, 255));
        lblIniciarEleicao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIniciarEleicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIniciarEleicaoMouseClicked(evt);
            }
        });
        getContentPane().add(lblIniciarEleicao);
        lblIniciarEleicao.setBounds(628, 8, 26, 24);

        jdpHome.setBackground(new java.awt.Color(246, 246, 246));
        getContentPane().add(jdpHome);
        jdpHome.setBounds(0, 40, 700, 460);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pu_adm_home_erroeleicao.png"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 698, 500);

        setSize(new java.awt.Dimension(698, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        frmLogin frm = new frmLogin();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSairMouseClicked

    private void lblCandidatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCandidatosMouseClicked
        frmEleitores.setVisible(false);
        frmRelatorios.setVisible(false);
        frmEleicao.setVisible(false);
        frmCandidatos.setVisible(true);
        frmCandidatos.carregaCombos();
        frmCandidatos.limparCampos();
    }//GEN-LAST:event_lblCandidatosMouseClicked

    private void lblEleitoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEleitoresMouseClicked
        frmRelatorios.setVisible(false);
        frmCandidatos.setVisible(false);
        frmEleicao.setVisible(false);
        frmEleitores.setVisible(true);
        frmEleitores.limparCampos();
        frmEleitores.carregarAlunos();

    }//GEN-LAST:event_lblEleitoresMouseClicked

    private void lblRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRelatoriosMouseClicked
        frmEleitores.setVisible(false);
        frmCandidatos.setVisible(false);
        frmEleicao.setVisible(false);
        frmRelatorios.setVisible(true);
        frmRelatorios.carregaCombos();
    }//GEN-LAST:event_lblRelatoriosMouseClicked

    private void lblIniciarEleicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarEleicaoMouseClicked
        frmEleitores.setVisible(false);
        frmCandidatos.setVisible(false);
        frmRelatorios.setVisible(false);
        frmEleicao.setVisible(true);
        frmEleicao.limpaData();
    }//GEN-LAST:event_lblIniciarEleicaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdpHome;
    private javax.swing.JLabel lblCandidatos;
    private javax.swing.JLabel lblEleitores;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblIniciarEleicao;
    private javax.swing.JLabel lblRelatorios;
    private javax.swing.JLabel lblSair;
    // End of variables declaration//GEN-END:variables
}
